-- Run this SQL in your Supabase SQL Editor to set up the notes table

-- Create the notes table
create table notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text default 'Untitled Note',
  content text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table notes enable row level security;

-- Create policies
create policy "Users can create their own notes"
on notes for insert
with check ( auth.uid() = user_id );

create policy "Users can view their own notes"
on notes for select
using ( auth.uid() = user_id );

create policy "Users can update their own notes"
on notes for update
using ( auth.uid() = user_id );

create policy "Users can delete their own notes"
on notes for delete
using ( auth.uid() = user_id );
